IF (OBJECT_ID('tempdb..#csv_temp') IS NOT NULL) DROP TABLE #csv_temp;

CREATE TABLE #csv_temp (
    ACCOUNT_RK CHAR(20),
	INTERNAL_ORG_ORIGINAL_RK CHAR(30),
	LOAN_AMOUNT CHAR(20),
	APPLICATION_DT CHAR(20)
);

BULK INSERT #csv_temp
FROM 'A:\data.csv'
WITH (fieldterminator = ';', rowterminator = '\n');

DELETE FROM #csv_temp WHERE ACCOUNT_RK = 'ACCOUNT_RK';

IF (OBJECT_ID('Positions') IS NOT NULL)DROP TABLE dbo.Positions;

CREATE TABLE Positions (
	INTERNAL_ORG_ORIGINAL_RK INT NOT NULL PRIMARY KEY,
);

BEGIN TRAN;
INSERT INTO dbo.Positions
SELECT DISTINCT CAST(INTERNAL_ORG_ORIGINAL_RK AS INT)
FROM #csv_temp;
COMMIT TRAN;

IF (OBJECT_ID('CSV_Export') IS NOT NULL) DROP TABLE dbo.CSV_Export;

CREATE TABLE CSV_Export (
	ACCOUNT_RK INT NOT NULL PRIMARY KEY,
	INTERNAL_ORG_ORIGINAL_RK INT NOT NULL FOREIGN KEY (INTERNAL_ORG_ORIGINAL_RK) REFERENCES Positions(INTERNAL_ORG_ORIGINAL_RK),
	LOAN_AMOUNT FLOAT NOT NULL,
	APPLICATION_DT DATETIME NOT NULL
);

BEGIN TRAN;
INSERT INTO dbo.CSV_Export
SELECT CAST(ACCOUNT_RK AS INT), CAST(INTERNAL_ORG_ORIGINAL_RK AS INT), CAST(LOAN_AMOUNT AS FLOAT), TRY_PARSE(APPLICATION_DT AS datetime)
FROM #csv_temp;

COMMIT TRAN;