SELECT DT.APPLICATION_DT, Pos.INTERNAL_ORG_ORIGINAL_RK, isnull(SUM(CSV_Export.LOAN_AMOUNT), 0) AS Amount
FROM 
	(SELECT DISTINCT APPLICATION_DT FROM dbo.CSV_Export) AS DT
CROSS JOIN 
	(SELECT Positions.INTERNAL_ORG_ORIGINAL_RK FROM dbo.Positions) AS Pos
LEFT OUTER JOIN 
	dbo.CSV_Export AS CSV_Export 
			ON DT.APPLICATION_DT = CSV_Export.APPLICATION_DT AND Pos.INTERNAL_ORG_ORIGINAL_RK = CSV_Export.INTERNAL_ORG_ORIGINAL_RK
GROUP BY DT.APPLICATION_DT, Pos.INTERNAL_ORG_ORIGINAL_RK
ORDER BY DT.APPLICATION_DT, Pos.INTERNAL_ORG_ORIGINAL_RK;